http://web.stanford.edu/class/cs20si/lectures/slides_02.pdf

In [217]:
import tensorflow as tf

### Visualize it with TensorBoard

In [9]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    # add this line to use TensorBoard.
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print (sess.run(x))
writer.close() # close the writer when you’re done using it

5


**tensorboard --logdir="graphs" --port 6006**

### How to change Const, Const_1 to the names we give the variables?

In [108]:
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
with tf.Session() as sess:
    writer = tf.summary.FileWriter("./graphs", sess.graph)
    print (sess.run(x)) # >> 5

5


### More constants

In [234]:
tf.reset_default_graph()

In [220]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
with tf.Session() as sess:
    x, y = sess.run([x, y])

In [221]:
x

array([[2, 3],
       [4, 5]], dtype=int32)

In [19]:
y

array([[0, 2],
       [4, 6]], dtype=int32)

In [22]:
tf.Session().run(tf.zeros([2, 3], tf.int32))

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
tf.Session().run(tf.zeros_like([[1,2],[2,3],[3,4]]))

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [27]:
tf.Session().run(tf.ones([2, 3], dtype=tf.float32, name=None))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [28]:
tf.Session().run(tf.ones_like([[1,2],[2,3],[3,4]], dtype=None, name=None, optimize=True))

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [30]:
tf.Session().run(tf.fill([2, 3], 8))

array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [31]:
tf.Session().run(tf.linspace(10.0, 13.0, 4))

array([ 10.,  11.,  12.,  13.], dtype=float32)

In [32]:
tf.Session().run(tf.range(3, 18, 3))

array([ 3,  6,  9, 12, 15], dtype=int32)

In [33]:
tf.Session().run(tf.range(5))

array([0, 1, 2, 3, 4], dtype=int32)

#### Randomly

In [222]:
tf.Session().run(tf.random_normal([2,3])) #Outputs random values from a normal distribution.

array([[ 0.12791388,  0.51015985,  1.54977   ],
       [ 0.73158234, -1.5680182 , -0.13328344]], dtype=float32)

In [55]:
tf.Session().run(tf.random_normal([2,3], mean=0., stddev=1.))

array([[ 1.13067174,  0.51460356, -0.34234586],
       [-0.25227457, -0.41949126,  0.13287899]], dtype=float32)

In [41]:
tf.Session().run(tf.truncated_normal([2,3]))

array([[ 0.17473085, -0.66943228,  0.39418778],
       [ 1.32886875, -1.12630033,  1.5188514 ]], dtype=float32)

In [42]:
tf.Session().run(tf.random_uniform([2,3])) #Outputs random values from a uniform distribution.

array([[ 0.65454996,  0.36397123,  0.6742816 ],
       [ 0.87555492,  0.70410192,  0.60370827]], dtype=float32)

In [48]:
tf.Session().run(tf.random_shuffle([1,2,3,4,5,6]))

array([4, 6, 1, 5, 3, 2], dtype=int32)

In [54]:
tf.Session().run(tf.random_crop([1,2,3,4,5,6], [2]))

array([4, 5], dtype=int32)

In [239]:
tf.Session().run(tf.multinomial(tf.log([[10., 10.]]), 5))

array([[0, 1, 1, 0, 1]])

In [237]:
tf.Session().run(tf.log([[10., 10.]]))

array([[ 2.30258512,  2.30258512]], dtype=float32)

In [233]:
#tf.Session(config=tf.ConfigProto(allow_soft_placement=True)).run(tf.multinomial([[1, -1, -1]], 10))
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
sess.run(tf.multinomial([[1, -1, -1]], 10))

InvalidArgumentError: No OpKernel was registered to support Op 'Multinomial' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]

	 [[Node: multinomial_4/Multinomial = Multinomial[T=DT_INT32, seed=0, seed2=0](multinomial_4/logits, multinomial_4/Multinomial/num_samples)]]

Caused by op 'multinomial_4/Multinomial', defined at:
  File "/Users/Seobs/miniconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Seobs/miniconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 498, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-233-1e0afebdea04>", line 3, in <module>
    sess.run(tf.multinomial([[1, -1, -1]], 10))
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/ops/random_ops.py", line 355, in multinomial
    seed2=seed2)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_random_ops.py", line 44, in multinomial
    seed2=seed2, name=name)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Multinomial' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]

	 [[Node: multinomial_4/Multinomial = Multinomial[T=DT_INT32, seed=0, seed2=0](multinomial_4/logits, multinomial_4/Multinomial/num_samples)]]


### Operations

In [63]:
a = tf.constant([3, 6])
b = tf.constant([2, 2])
tf.add(a, b) # >> [5 8]
tf.add_n([a, b, b]) # >> [7 10]. Equivalent to a + b + b
tf.multiply(a, b) # >> [6 12] because mul is element wise
tf.matmul(a, b) # >> ValueError
tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1])) # >> [[18]]
tf.div(a, b) # >> [1 3]
tf.mod(a, b) # >> [1 0]

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2], [2].

In [246]:
tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1])) # >> [[18]]
tf.div(a, b) # >> [1 3]
tf.mod(a, b) # >> [1 0]

<tf.Tensor 'FloorMod:0' shape=(2,) dtype=int32>

#### Constants are stored in the graph definition

In [110]:
my_const = tf.constant([1.0, 2.0], name="my_const")

with tf.Session() as sess:
    print (sess.graph.as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Variable/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "Variable/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32


In [67]:
a = tf.Variable(2, name="scalar") 

In [68]:
b = tf.Variable([2, 3], name="vector") 

In [69]:
c = tf.Variable([[0, 1], [2, 3]], name="matrix") 

In [70]:
W = tf.Variable(tf.zeros([784,10]))

### wait

In [126]:
tf.reset_default_graph()

In [127]:
a = tf.constant(3, name='a')

In [128]:
b = tf.Variable(3, name='b')

In [132]:
[n.name for n in tf.get_default_graph().as_graph_def().node]

['a', 'b/initial_value', 'b', 'b/Assign', 'b/read']

In [123]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

In [166]:
init_ab = tf.variables_initializer([b], name="init_ab")
#a = tf.Variable(3)
a = tf.constant(3)
with tf.Session() as sess:
    #init_ab = tf.variables_initializer([a], name="init_ab")
    sess.run(init_ab)

In [83]:
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)

In [161]:
with tf.Session() as S:
    V = tf.Variable(tf.linspace(0., 100., 10))
    S.run(tf.variables_initializer([V]))

In [168]:
# W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W)

Tensor("Variable_4/read:0", shape=(700, 10), dtype=float32)


In [169]:
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W.eval())

[[-1.82264209  0.36588758 -1.04991889 ...,  1.11181867  0.57185662
   0.44481242]
 [-0.18719493  0.18903789 -0.32622156 ...,  1.47339725  1.77950382
  -0.37856391]
 [ 0.85419846 -0.42952034 -0.09131973 ...,  0.14342438 -0.22254217
  -0.17048967]
 ..., 
 [ 0.56427121 -0.50641471 -0.07579794 ...,  0.48155406 -0.97503293
  -0.56444341]
 [ 0.52177972  0.07482305  0.50341469 ...,  0.10426363  0.53495103
  -0.01941857]
 [ 1.18114829  0.97057432 -0.08434246 ..., -0.61878818  0.17771073
   1.13732266]]


In [176]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W.eval())

10


In [178]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print (W.eval())

100


In [180]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    #sess.run(W.initializer)
    sess.run(assign_op)
    print (W.eval())

100


In [190]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))

4
8


In [192]:
my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    
    print(sess.run(my_var.assign_add(10)))
    print(sess.run(my_var.assign_sub(2)))

20
18


In [199]:
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print (sess1.run(W.assign_add(10)))
print (sess2.run(W.assign_sub(2)))

20
8


In [200]:
print (sess1.run(W.assign_add(100)))
print (sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

120
-42


In [201]:
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(2 * W)

In [209]:
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(2 * W.initialized_value())

#### InteractiveSession

In [210]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

print(c.eval())
sess.close()

30.0


#### placeholder

In [247]:
a = tf.placeholder(tf.float32, shape=[3])

In [248]:
b = tf.constant([5, 5, 5], tf.float32)

In [249]:
c = a + b 

In [251]:
with tf.Session() as sess:
    print (sess.run(c))

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/Users/Seobs/miniconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Seobs/miniconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 498, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-247-31c0a4f95946>", line 1, in <module>
    a = tf.placeholder(tf.float32, shape=[3])
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1520, in placeholder
    name=name)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/Seobs/miniconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


In [253]:
with tf.Session() as sess:
    print (sess.run(c, {a: [1, 2, 3]}))

[ 6.  7.  8.]


#### Feeding values to TF ops 

In [4]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

In [8]:
with tf.Session() as sess:
    # define a dictionary that says to replace the value of 'a' with 15
    replace_dict = {a: 15}
    
    # Run the session, passing in 'replace_dict' as the value to 'feed_dict'
    print (sess.run(b, feed_dict=replace_dict)) # returns 45

45


#### Lazy loading Example

In [9]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # you create the node for add node before executing the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        sess.run(z)
    writer.close()

In [10]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        sess.run(tf.add(x, y)) # someone decides to be clever to save one line of code
    writer.close()